### ISSUE TITLE
UltraNest support

### ISSUE THREAD

**Issue by JohannesBuchner** [LucaMalavolta/PyORBIT#20]
Would you be interested to add support for https://johannesbuchner.github.io/UltraNest/ ?
The interface should be very similar to dynesty.
UltraNest is a very reliable tuning-parameter-free algorithm. It can be faster than dynesty, especially if you take advantage of vectorization.
It also supports resuming from disk and MPI parallelisation, if that is useful to you.

**Comment by LucaMalavolta** [comment]
Dear Johannes,
Believe it or not, I added UltraNest support before reading this message (i.e. right now). 
You may have not seen it until recently because I am working on the code on a private development branch before pushing it to the main repository. 
I tested your code and it works very well, thank you very much for your work!
Cheers,
Luca
